# Generated by Django 5.2.5 on 2026-03-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activitate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=200)),
                ('descriere', models.TextField()),
                ('data', models.DateField()),
                ('categorie', models.CharField(max_length=100)),
                ('imagine', models.ImageField(blank=True, upload_to='activitati/')),
            ],
        ),
    ]
