# Generated by Django 5.2.5 on 2026-03-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitati', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitate',
            name='coordonator',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
